name: Build and Push Docker Image
description: Build and push Docker image to AWS ECR and/or Docker Hub

inputs:
  context:
    description: Build context (path to the directory containing the Dockerfile)
    default: ./
    required: true
  dockerfile:
    description: Path to the Dockerfile relative to the context
    required: true
    default: Dockerfile
  env_type:
    description: Environment type (e.g., STAGING, PRODUCTION)
    required: true
  registry_hostname:
    description: Docker Hub registry hostname
    required: true
    default: docker.io
  project:
    description: Docker project name
    required: true
  push_to_aws:
    description: Push to AWS ECR (true/false)
    required: false
    default: false
  push_to_dockerhub:
    description: Push to Docker Hub (true/false)
    required: false
    default: true
  docker_username:
    description: Docker Hub username
    required: true
  docker_password:
    description: Docker Hub password or access token
    required: true
  GITHUB_RUN_ID:
    required: true
  GITHUB_SHA:
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Docker Image Name
      id: generate-name
      run: |
        BUILD_ID="${{ inputs.GITHUB_RUN_ID }}"
        GIT_COMMIT="${{ inputs.GITHUB_SHA }}"
        IMAGE_NAME="${BUILD_ID}_${{ inputs.env_type }}_${GIT_COMMIT}"
        DOCKER_BUILD_NAME="${{ inputs.registry_hostname }}/${{ inputs.project }}:${IMAGE_NAME}"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "DOCKER_BUILD_NAME=$DOCKER_BUILD_NAME" >> $GITHUB_ENV
      shell: bash # Указание оболочки для выполнения команд

    - name: Configure AWS Credentials
      if: ${{ inputs.push_to_aws == 'true' }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::874733548478:role/GitHubOIDC
        aws-region: eu-central-1

    - name: Login to AWS ECR
      if: ${{ inputs.push_to_aws == 'true' }}
      uses: aws-actions/amazon-ecr-login@v1

    - name: Login to Docker Hub
      if: ${{ inputs.push_to_dockerhub == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: |
          ${{ env.DOCKER_BUILD_NAME }}
        push: true

    - name: Tag and Push to AWS ECR
      if: ${{ inputs.push_to_aws == 'true' }}
      run: |
        AWS_ECR_TAG="874733548478.dkr.ecr.eu-central-1.amazonaws.com/${{ inputs.project }}:${IMAGE_NAME}"
        docker tag "$DOCKER_BUILD_NAME" "$AWS_ECR_TAG"
        docker push "$AWS_ECR_TAG"
        echo "Pushed to AWS ECR: $AWS_ECR_TAG"
      shell: bash # Указание оболочки для выполнения команд
