name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: your-org/your-actions-repo/.github/actions/docker-build-and-push.yml@main
        with:
          context: ./apps/core-api
          dockerfile: Dockerfile
          env_type: STAGING
          registry_hostname: docker.io
          project: sandbox-api
          push_to_aws: true
          push_to_dockerhub: true
        env:
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: 123456789012
