name: Deploy Frontend

on:
  workflow_call:
    inputs:
      folder_name:
        required: true
        type: string
      node_version:
        required: true
        type: string
      build_command:
        required: true
        type: string
      deploy_url:
        required: true
        type: string
      environment:
        required: true
        type: string
      validate_env_command:
        required: false
        type: string
      source_path:
        required: false
        type: string
        default: 'build'
    secrets:
      kube_config:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  FOLDER_NAME: ${{ inputs.folder_name }}
  KUBE_CONFIG_BASE64: ${{ secrets.kube_config }}
  CI: false
  SOURCE: ${{ inputs.source_path }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:${{ inputs.node_version }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.deploy_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          ./aws/install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Dependencies
        uses: it-incubator/ci-cd-pipeplines/.github/actions/manage-packages@master
        with:
          command: install

      - name: Validate environment
        if: ${{ inputs.validate_env_command != '' }}
        uses: it-incubator/ci-cd-pipeplines/.github/actions/manage-packages@master
        with:
          command: ${{ inputs.validate_env_command }}

      - name: Build project
        uses: it-incubator/ci-cd-pipeplines/.github/actions/manage-packages@master
        with:
          command: ${{ inputs.build_command }}

      - name: Setup KubeConfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_BASE64" | base64 -d > ~/.kube/config

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Ensure EFS target dir exists in pod
        run: |
          POD=$(kubectl get pod -l app=multi-frontend -n multi-frontend -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -n multi-frontend "$POD" -- mkdir -p /usr/share/nginx/html/$FOLDER_NAME

      - name: Copy frontend files to pod's EFS
        run: |
          POD=$(kubectl get pod -l app=multi-frontend -n multi-frontend -o jsonpath="{.items[0].metadata.name}")
          kubectl cp ./$SOURCE/. "$POD":/usr/share/nginx/html/$FOLDER_NAME -n multi-frontend
